In [ ]:
x1, x2, w1, w2, b = 6, 5, 3, 1, -25

x1*w1 + x2*w2 + b

In [ ]:
import numpy as np

def perceptron(x,W,b):
    return np.matmul(x,W)+b >= 0


x = [6,2,4,2,7,8]
W = [3,1,1,9,5,3]
b = -25
perceptron(x,W,b)

In [ ]:
#Perceptron Training

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_excel(r"C:\Users\mg\Desktop\intro to DL\data.xlsx", header=None)
X = np.array([df[0], df[1]])
y = np.array(df[2])

plt.scatter(X[0][np.where(y==1)], X[1][np.where(y==1)], color='blue')
plt.scatter(X[0][np.where(y==0)], X[1][np.where(y==0)], color='red')

plt.show()

In [ ]:
def prediction(x, W, b):
    return np.matmul(x,W)+b >= 0

def perceptronStep(X, y, W, b, lr):
    for i in range(len(X)):
        y_hat = prediction(X[i], W, b)
        
        if y[i] - y_hat == 1:
            W[0] += X[i][0] * lr
            W[1] += X[i][1] * lr
            b += lr
        elif y[i] - y_hat == -1:
            W[0] -= X[i][0] * lr
            W[1] -= X[i][1] * lr
            b -= lr
            
    return W, b

def trainPerceptron(X, y, lr, n_epochs):
    W = np.array(np.random.rand(2,1))
    b = 2
    lines = []
    
    for i in range(n_epochs):
        lines.append((-W[0]/W[1], -b/W[1]))
        W, b = perceptronStep(X, y, W, b, lr)
        
    return lines



In [ ]:
res = trainPerceptron(X.T, y, lr=0.1, n_epochs=35)



def abline(slope, intercept):
    """Plot a line from slope and intercept"""
    axes = plt.gca()
    x_vals = np.array(axes.get_xlim())
    y_vals = intercept + slope * x_vals
    plt.plot(x_vals, y_vals, '--')

    
for i in range(len(res)):
    plt.scatter(X[0][np.where(y==1)], X[1][np.where(y==1)], color='blue')
    plt.scatter(X[0][np.where(y==0)], X[1][np.where(y==0)], color='red')
    abline(res[i][0], res[i][1])
    plt.show()

In [ ]:
#Softmax

In [ ]:
import numpy as np

def softmax(L):
    exps = np.exp(L)
    sumOfExps = sum(exps)
    
    res = []
    for i in exps:
        res.append(i/sumOfExps)
    return res

softmax([2,1,0])

In [ ]:
import numpy as np

def softmax(L):
    exps = np.exp(L)
    sumOfExps = sum(exps)
    
    return [i/sumOfExps for i in exps]

softmax([2,1,0])

In [ ]:
#Logistic Regression

In [ ]:
import numpy as np

def crossEntropy(y, output):
    return -y*np.log(output) - (1-y) * np.log(1-output)

def sigmoid(x):
    return 1/(1+np.exp(-x))

def outputFormula(x, W, bias):
    return sigmoid(np.dot(x,W)+bias)

# Logistic Regression

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#Some helper functions for plotting and drawing lines

def plot_points(X, y):
    admitted = X[np.argwhere(y==1)]
    rejected = X[np.argwhere(y==0)]
    plt.scatter([s[0][0] for s in rejected], [s[0][1] for s in rejected], s = 25, color = 'red', edgecolor = 'k')
    plt.scatter([s[0][0] for s in admitted], [s[0][1] for s in admitted], s = 25, color = 'green', edgecolor = 'k')

def display(m, b, color='g--'):
    plt.xlim(-0.05,1.05)
    plt.ylim(-0.05,1.05)
    x = np.arange(-10, 10, 0.1)
    plt.plot(x, m*x+b, color)

In [ ]:
data = pd.read_csv('data.csv', header=None)
X = np.array(data[[0,1]])
y = np.array(data[2])
plot_points(X,y)
plt.show()

In [ ]:
import numpy as np

def error_formula(y, output):
    return -y*np.log(output) - (1-y) * np.log(1-output)

def sigmoid(x):
    return 1/(1+np.exp(-x))

def outputFormula(x, W, bias):
    return sigmoid(np.dot(x,W)+bias)

def update_weights(x, y, weights, bias, lr):
    output = outputFormula(x, weights, bias)
    d_error = y - output
    weights += lr * d_error * x
    bias += lr * d_error
    return weights, bias

In [ ]:
np.random.seed(44)
epochs = 400
lr = 0.001

def train(features, targets, epochs, lr):
    errors = []
    n_records, n_features = features.shape
    
    weights = np.random.normal(size = n_features)
    bias = 0
    
    for e in range(epochs):
        for x, y in zip(features, targets):
            output = outputFormula(x, weights, bias)
            error = error_formula(y, output)
            weights, bias = update_weights(x, y, weights, bias, lr)
            
        out = outputFormula(features, weights, bias)
        loss = np.mean(error_formula(targets, out))
        errors.append(loss)
        
        if e % (epochs/10) == 0:
            print("\n ========Epoch",e,"=========")
            print("Train Loss", loss)
            predictions = out > 0.5
            accuracy = np.mean(predictions == targets)
            print("Accuracy: ", accuracy)
            
            display(-weights[0]/weights[1], -bias/weights[1])
            
            
    #Solution Boudary
    plt.title("Solution Boudary")
    display(-weights[0]/weights[1], -bias/weights[1], 'black')
    
    plot_points(features, targets)
    plt.show()
    
    
    #Plotting the error
    plt.title("Error Plot")
    plt.xlabel("Number of Epochs")
    plt.ylabel("Error")
    plt.plot(errors)
    plt.show()

In [ ]:
train(X, y, epochs, lr)

# Neural Network

In [ ]:
import pandas as pd
import numpy as np

data = pd.read_csv('student_data.csv')

data.head()

In [ ]:
import matplotlib.pyplot as plt

def plot_points(data):
    X = np.array(data[["gre","gpa"]])
    y = np.array(data["admit"])
    admitted = X[np.argwhere(y==1)]
    rejected = X[np.argwhere(y==0)]
    plt.scatter([s[0][0] for s in rejected], [s[0][1] for s in rejected], s = 25, color = 'red', edgecolor = 'k')
    plt.scatter([s[0][0] for s in admitted], [s[0][1] for s in admitted], s = 25, color = 'cyan', edgecolor = 'k')
    plt.xlabel('Test (GRE)')
    plt.ylabel('Grades (GPA)')
    
plot_points(data)
plt.show()

In [ ]:
# Separating the ranks
data_rank1 = data[data["rank"]==1]
data_rank2 = data[data["rank"]==2]
data_rank3 = data[data["rank"]==3]
data_rank4 = data[data["rank"]==4]

# Plotting the graphs
plot_points(data_rank1)
plt.title("Rank 1")
plt.show()
plot_points(data_rank2)
plt.title("Rank 2")
plt.show()
plot_points(data_rank3)
plt.title("Rank 3")
plt.show()
plot_points(data_rank4)
plt.title("Rank 4")
plt.show()

In [ ]:
hot_encode = pd.concat([data, pd.get_dummies(data['rank'], prefix = 'rank')], axis = 1)
hot_encode = hot_encode.drop('rank', axis = 1)
hot_encode[:5]

In [ ]:
processed_data = hot_encode[:]

processed_data['gpa'] = processed_data['gpa'] / processed_data['gpa'].max()
processed_data['gre'] = processed_data['gre'] / processed_data['gre'].max()

processed_data[:5]

In [ ]:
sample = np.random.choice(processed_data.index, size = int(len(processed_data)*0.9), replace = False)
train_data, test_data = processed_data.iloc[sample], processed_data.drop(sample)

print("Size of Training:", len(train_data))
print("Size of Testing:", len(test_data))

In [ ]:
features = train_data.drop('admit', axis=1)
targets = train_data['admit']

test_features = test_data.drop('admit', axis=1)
targets_test = test_data['admit']

In [ ]:
def error_formula(y, output):
    return -y*np.log(output) - (1-y) * np.log(1-output)

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_prime(x):
    return sigmoid(x) * (1 - sigmoid(x))

def error_term_formula(x, yhat, y):
    return (y - yhat)*x

In [ ]:
def NN(features, targets, epochs = 1000, lr = 0.01):
    np.random.seed(42)
    n_records, n_features = features.shape
    
    weights = np.random.normal(size = n_features)
    
    for epoch in range(epochs):
        del_w = np.zeros(weights.shape)
        for x, y in zip(features.values, targets):
            yhat = sigmoid(np.dot(x, weights))
            error_term = error_term_formula(x, yhat, y)
            del_w += error_term
            
        weights += lr * del_w
    
        if epoch % (epochs / 10) == 0:
            out = (sigmoid(np.dot(features, weights)))
            loss = np.mean(error_formula(targets, out))

            print("Epoch:", epoch)
            print("Training Loss:", loss,"\n==============")
    return weights

weights = NN(features, targets)

In [ ]:
test_out = sigmoid(np.dot(test_features, weights))
predictions = test_out > 0.5

accuracy = np.mean(predictions == targets_test)

print("Accuracy: ", accuracy)

# Final Project

In [1]:
import numpy as np
import pandas as pd

In [2]:
iris = pd.read_csv("Iris.csv")
iris = iris.sample(frac=1).reset_index(drop=True)
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0     52            6.4           3.2            4.5           1.5   
1     80            5.7           2.6            3.5           1.0   
2     29            5.2           3.4            1.4           0.2   
3     69            6.2           2.2            4.5           1.5   
4     17            5.4           3.9            1.3           0.4   
..   ...            ...           ...            ...           ...   
145   98            6.2           2.9            4.3           1.3   
146  110            7.2           3.6            6.1           2.5   
147  139            6.0           3.0            4.8           1.8   
148   16            5.7           4.4            1.5           0.4   
149  145            6.7           3.3            5.7           2.5   

             Species  
0    Iris-versicolor  
1    Iris-versicolor  
2        Iris-setosa  
3    Iris-versicolor  
4        Iris-setosa  
..               ...  
145  Iris-versicolor  
146   Iris-virginica  
147   Iris-virginica  
148      Iris-setosa  
149   Iris-virginica  

[150 rows x 6 columns]

In [3]:
X = iris[['SepalLengthCm','SepalWidthCm', 'PetalLengthCm','PetalWidthCm']]
X = np.array(X)
X[:5]

array([[6.4, 3.2, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [6.2, 2.2, 4.5, 1.5],
       [5.4, 3.9, 1.3, 0.4]])

In [4]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder(sparse = False)

Y = iris.Species
Y = one_hot_encoder.fit_transform(np.array(Y).reshape(-1,1))
Y[:5]

array([[0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.15)
X_train, X_val, Y_train, Y_val = train_test_split(X_train, Y_train, test_size = 0.1)

In [56]:
Y_train

array([[0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0

In [17]:
def initWeights(nodes):
    layers, weights = len(nodes), []
    
    for i in range(1, layers):
        w = [[np.random.uniform(-1,1) for k in range(nodes[i-1] + 1)] for j in range(nodes[i])]
        weights.append(np.matrix(w))
        
    return weights

In [7]:
def feedForward(x, weights, layers):
    activations, layer_input = [x], x
    
    for j in range(layers):
        activation = sigmoid(np.dot(layer_input, weights[j].T))
        activations.append(activation)
        layer_input = np.append(1, activation)
        
    return activations

In [8]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoidDerivative(x):
    return np.multiply(x, 1-x)

In [21]:
def backPropagation(y, activations, weights, layers):
    outputFinal = activations[-1]
    error = np.matrix(y - outputFinal)
    
    for j in range(layers, 0, -1):
        currentActivation = activations[j]
        
        if(j>1):
            prevActivation = np.append(1, activations[j-1])
        else:
            prevActivation = activations[0]
            
        delta = np.multiply(error, sigmoidDerivative(currentActivation))
        weights[j-1] += lr * np.multiply(delta.T, prevActivation)

        w = np.delete(weights[j-1], [0], axis=1)
        error = np.dot(delta, w)
    
    return weights
    

In [22]:
def train(X, Y, lr, weights):
    layers = len(weights)
    
    for i in range(len(X)):
        x, y = X[i], Y[i]
        x = np.matrix(np.append(1,x))
        activations = feedForward(x, weights, layers)
        weights = backPropagation(y, activations, weights, layers)
        
    return weights

In [43]:
def predict(item, weights):
    layers = len(weights)
    item = np.append(1, item)
    
    activations = feedForward(item, weights, layers)
    output = activations[-1].A1
    max_index = np.argmax(output)
    
    yhat = [0 for i in range(len(output))]
    yhat[max_index] = 1
    
    return yhat

In [66]:
def accuracy(X, Y, weights):
    correct = 0
    
    for i in range(len(X)):
        x, y = X[i], list(Y[i])
        guess = predict(x, weights)
        if(y == guess):
            correct += 1
    return correct/len(X)

In [67]:
def NeuralNetwork(X_train, Y_train, X_val = None, Y_val = None, epochs = 10, nodes = [], lr=0.15):
    hidden_layers = len(nodes) - 1
    weights = initWeights(nodes)
    
    for epoch in range(epochs+1):
        weights = train(X_train, Y_train, lr, weights)
        
        if(epoch%20 == 0):
            print("Epoch:", epoch)
            print("Training Accuracy:", accuracy(X_train, Y_train, weights))
            print("Validation Accuracy:", accuracy(X_val, Y_val, weights))
            
    return weights

In [68]:
num_of_features = len(X[0])
num_of_outputs = len(Y[0])

layers = [num_of_features, 5, 8, num_of_outputs]
lr, epochs = 0.15, 100

weights = NeuralNetwork(X_train, Y_train, X_val, Y_val, epochs = epochs, nodes = layers, lr = lr)

Epoch: 0
Training Accuracy: 0.34210526315789475
Validation Accuracy: 0.15384615384615385
Epoch: 20
Training Accuracy: 0.9210526315789473
Validation Accuracy: 0.8461538461538461
Epoch: 40
Training Accuracy: 0.8771929824561403
Validation Accuracy: 0.7692307692307693
Epoch: 60
Training Accuracy: 0.9298245614035088
Validation Accuracy: 0.8461538461538461
Epoch: 80
Training Accuracy: 0.9385964912280702
Validation Accuracy: 0.8461538461538461
Epoch: 100
Training Accuracy: 0.9473684210526315
Validation Accuracy: 0.8461538461538461


In [69]:
print("Testing Accuracy:", accuracy(X_test, Y_test, weights))

Testing Accuracy: 1.0
